MGMWeatherApp/WEB/Controllers/StationController.cs
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using WEB.ViewModels;

namespace WEB.Controllers
{
    public class StationController : Controller
    {
        private readonly IStationService _stationService;
        private readonly IFihristService _fihristService;

        public StationController(IStationService stationService, IFihristService fihristService)
        {
            _stationService = stationService;
            _fihristService = fihristService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            var vm = new StationCreateViewModel();
            return View(vm);
        }

        [HttpPost]
        public IActionResult Create(StationCreateViewModel vm)
        {
            try
            {
                _stationService.Add(new Station
                {
                    Name = vm.Name ?? "",
                    CityDistrictId = vm.SelectedDistrictId,
                    GoogleMapLink = vm.GoogleMapsUrl ?? "",
                    ICAO = vm.ICAO,
                    StationNo = vm.StationNumber,
                    IsActive = vm.IsActive,
                });
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.InnerException.Message;
                return View(vm);
            }
        }

        public IActionResult Update(int? stationId)
        {
            var result = _stationService.GetStationDetailById(stationId.Value).Data;

            var vm = new StationUpdateViewModel()
            {
                Id = result.Id,
                Name = result.StationName,
                SelectedCityId = result.CityId,
                SelectedDistrictId = result.DistrictId,
                GoogleMapsUrl = result.GoogleMapLink,
                ICAO = result.ICAO,
                StationNumber = result.StationNo,
                IsActive =result.IsActive
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Update(StationUpdateViewModel vm)
        {
            try
            {
                _stationService.Update(new Station
                {
                    Id = vm.Id,
                    Name = vm.Name ?? "",
                    CityDistrictId = vm.SelectedDistrictId,
                    GoogleMapLink = vm.GoogleMapsUrl ?? "",
                    ICAO = vm.ICAO,
                    StationNo = vm.StationNumber,
                    IsActive = vm.IsActive
                });
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.InnerException.Message;
                return View(vm);
            }
        }

        public JsonResult GetStations(int? cityId)
        {
            var stations = new List<StationUpdateViewModel>();
            _stationService.GetStationListByCityId(cityId.Value).Data.ForEach(x => stations.Add(new StationUpdateViewModel
            {
                Id = x.Id,
                Name = x.StationName,
                ICAO = x.ICAO ?? "-",
                District = x.DistrictName,
                GoogleMapsUrl = x.GoogleMapLink,
                StationNumber = x.StationNo
            }));

            return Json(stations);
        }
    }
}

MGMWeatherApp/WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - WEB</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/adminlte/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/css/adminlte.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/adminlte/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/adminlte/plugins/summernote/summernote-bs4.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
</head>
<body class="hold-transition layout-top-nav light-mode">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
            <div class="container">
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <span class="brand-text font-weight-light">MGM</span>
                </a>

                <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                    <!-- Left navbar links -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Home")" class="nav-link">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Stadium")" class="nav-link">Stadyumlar</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Station")" class="nav-link">İstasyonlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- /.navbar -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @if (!string.IsNullOrEmpty(ViewBag?.ErrorMessage))
            {
                <section class="content">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">HATA</h3>
                        </div>
                        <div class="card-body">
                            <ul>
                                <li>@ViewBag?.ErrorMessage</li>
                            </ul>
                        </div>
                    </div>
                </section>
            }
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>@DateTime.Now.Year - MGM</strong>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/adminlte/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/adminlte/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/adminlte/plugins/select2/js/select2.full.min.js"></script>
    <script src="~/adminlte/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>

    <script src="~/adminlte/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/adminlte/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/adminlte/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/adminlte/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/adminlte/plugins/moment/moment.min.js"></script>
    <script src="~/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/adminlte/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/adminlte/js/pages/dashboard.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="~/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/jszip/jszip.min.js"></script>
    <script src="~/adminlte/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/adminlte/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="~/js/site.js"></script>
    <!-- AdminLTE for demo purposes -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>